---
title: 'HERT Data Viz Tutorial'
subtitle: 'RMarkdown and Mapping'
author: 'Randy Parrish'
date: '04/02/2021'
output: html_document
---


# RMarkdown Setup

```{r, setup}
knitr::opts_chunk$set(
  cache = FALSE, 
  error = TRUE, 
  warning = FALSE,
  tidy = FALSE,
  fig.align = 'center',
  message = FALSE)
```

```{r, functions}
# make HTML style tables
library(kableExtra)

# function to make the table from a data frame
report_table <- function(data, 
  w = NULL, h = '300px', ec = 'margin: 10px;', 
  rownames = FALSE, scroll = TRUE)
{
  # create the HTML table
  tbl <- kable_paper(
  kable_styling(
    kbl(data, 
      row.names = rownames), 
    full_width = T, 
    position = 'center',
    bootstrap_options = c('striped', 'hover'),
    fixed_thead = T), 
  full_width = T)

  # wrap it in a scroll box
  if (scroll) {
    tbl <- scroll_box(tbl, 
      fixed_thead = T, 
      height = h,
      width = w,
      extra_css = ec)
  }
  # return the table
  tbl
}
```

# Maps

## Libraries

```{r, options-libraries}
options(stringsAsFactors = FALSE)

# match country names between datasets
library(countrycode) 

# plotting spatial data
library(ggplot2)
library(rnaturalearth)
library(sf)
# 'sf' requires package 'units'; 
# installation help for 'units' package: https://github.com/r-quantities/units

# palette
library(scales)
```

## Data Set Up

```{r, data}
# read in region-country data
reg_con <- read.csv(
  'region_country.txt', 
  header = TRUE, 
  sep = '\t')

# show HTML table of data
report_table(reg_con)

# get 3 letter code for countries
reg_con$iso <- countrycode(
  reg_con$country, 
  origin = 'country.name', 
  destination = 'iso3c')

# get worldmap spatial data from rnaturalearth
worldmap <- ne_countries(
  scale = 'medium', 
  type = 'countries', 
  returnclass = 'sf')

# show HTML table of first 5 lines of data
report_table(head(as.data.frame(worldmap)))

# merge reg and worldmap on country code
dat <- merge(
  worldmap, 
  reg_con, 
  by.x = 'iso_a3', 
  by.y = 'iso', 
  all = TRUE)

# show HTML table of first 5 lines of data
report_table(head(as.data.frame(dat)))
```

## Palette Set Up

```{r, palette}
# list of unique regions
regions <- sort(unique(reg_con$who_region))

# set colors
gray <- '#c4c4c4'
blue <- '#0072B2'

# set palette
world_pal <- setNames(
  hue_pal(l = 70)(6)[c(5,1,2,6,3,4)], 
  regions)

# function to get palette for region mapping
region_pal <- function(region){
  other_regions <- setdiff(regions, region)
  other_pal <- rep(gray, length(other_regions))
  reg_pal <- setNames(c(blue, other_pal), c(region, other_regions))
  return(reg_pal)
}
```

## World Map

```{r, world-map, out.width='100%'}
# plot world map
world_p <- ggplot(data = dat) + 
  geom_sf(
    aes(fill = who_region), 
    lwd = 0.1, 
    color = 'white') + 
  theme_void() + 
  scale_fill_manual(
    values = world_pal, 
    na.value = gray) +
  theme(
    legend.position = 'none',
    plot.margin = grid::unit(c(0,0,0,0), 'mm'))

world_p
```


## Region Maps

```{r, region-maps}
# read in data of rectangle coordinates
# coordinates obtained using: https://boundingbox.klokantech.com/
reg_loc <- read.table(
  'reg_loc.txt', 
  header = TRUE, 
  sep = '\t',
  fileEncoding = 'UTF-8', 
  quote = '')

# show HTML table of data
report_table(reg_loc)

# function to get region map
region_map <- function(region){
  zoom <- reg_loc[reg_loc$region == region,]

  ggplot(data = dat) + 
    geom_sf(
      aes(fill = who_region), 
      lwd = 0.1, 
      color = 'white') +
    coord_sf(
      xlim = c(zoom$lon_min, zoom$lon_max), 
      ylim = c(zoom$lat_min, zoom$lat_max), 
      expand = FALSE) +
    theme_void() + 
    scale_fill_manual(
      values = region_pal(region), 
      na.value = gray) +
    theme(
      legend.position = 'none', 
      plot.margin = grid::unit(c(0,0,0,0), 'mm'))
}

# view region maps
region_map('Africa')
region_map('Americas')
region_map('Eastern Mediterranean')
region_map('Europe')
region_map('South-East Asia')
region_map('Western Pacific')
```

# More Resources

* ["Drawing beautiful maps programmatically with R, sf and ggplot2"](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html) - Mel Moreno & Mathieu Bastille

* ["Zooming in on maps with sf and ggplot2"](https://www.r-bloggers.com/2019/04/zooming-in-on-maps-with-sf-and-ggplot2/) - Markus Konrad
